version: '2'

services:

  nginx-proxy:
    hostname: nginx-proxy
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./vhost.d:/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./certs:/etc/nginx/certs:ro"
      - html:/usr/share/nginx/html
    networks:
      - frontend
  letsencrypt:
    hostname: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    #depends_on: nginx-proxy
    volumes:
      - "./certs:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./vhost.d:/etc/nginx/vhost.d"
      - html:/usr/share/nginx/html 
    networks:
      - frontend

networks:
  frontend:
    driver: bridge

volumes:
  html: 
