version: "3"

services:
  nginx-proxy:
    hostname: nginx-proxy
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./vhost.d:/etc/nginx/vhost.d"
      - "./custom.conf:/etc/nginx/conf.d/custom.conf"
      - "./certs:/etc/nginx/certs:ro"
      - html:/usr/share/nginx/html
    networks:
      - frontend
    restart: always
  letsencrypt:
    hostname: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    depends_on: [nginx-proxy]
    volumes:
      - "./certs:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./vhost.d:/etc/nginx/vhost.d"
      - html:/usr/share/nginx/html
    networks:
      - frontend
    restart: always

networks:
  frontend:
    driver: bridge

volumes:
  html:
