version: "3"

services:
  api:
    hostname: api
    container_name: api
    build:
      context: ./api
    command: npm start
    depends_on:
      - mongodb
      - auth
    volumes:
      - ./materials:/app/materials
      - /app/.config
      - ${SVG_DIR}:/app/svg:ro
      - ${IMAGE_DIR}:/app/pictograms
    environment:
      LETSENCRYPT_HOST: "api.arasaac.org"
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      VIRTUAL_HOST: "api.arasaac.org"
      NODE_ENV: $NODE_ENV
      EMAIL_FROM: $EMAIL_FROM
      EMAIL_USER: $EMAIL_USER
      EMAIL_PASSWORD: $EMAIL_PASSWORD
      EMAIL_VERIFICATION_URL: $EMAIL_VERIFICATION_URL
      MASTER_KEY: $MASTER_KEY
      JWT_SECRET: $JWT_SECRET
    networks:
      - nginxproxy_frontend
      - backend

  privateapi:
    hostname: privateapi
    container_name: privateapi
    build:
      context: ./privateApi
    command: npm start
    depends_on:
      - mongodb
      - auth
    volumes:
      - ./privateApi:/app
      - ./materials:/app/materials
      - ./locutions:/app/locutions
      - ./certs:/root/.ssh
      - ${IMAGE_DIR}:/app/pictograms
      - ./tmp:/app/tmp
      - /app/node_modules
      - /app/.config
    environment:
      LETSENCRYPT_HOST: "privateapi.arasaac.org"
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      VIRTUAL_HOST: "privateapi.arasaac.org"
      NODE_ENV: $NODE_ENV
      EMAIL_FROM: $EMAIL_FROM
      EMAIL_USER: $EMAIL_USER
      EMAIL_PASSWORD: $EMAIL_PASSWORD
      EMAIL_VERIFICATION_URL: $EMAIL_VERIFICATION_URL
    networks:
      - nginxproxy_frontend
      - backend

  auth:
    hostname: auth
    container_name: auth
    build:
      context: ./auth
    command: ./start-prod.sh
    depends_on:
      - mongodb
    volumes:
      - ./auth:/app
      - /app/node_modules
      - /app/.config
      - ./auth/src/certs:/app/dist/certs
    environment:
      LETSENCRYPT_HOST: "auth.arasaac.org"
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      VIRTUAL_HOST: "auth.arasaac.org"
      NODE_ENV: $NODE_ENV
    networks:
      - nginxproxy_frontend
      - backend

  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:3.6
    volumes:
      - ./mongodb/dump:/docker-entrypoint-initdb.d
      - ./mongodb/dbdata:/data/db
    networks:
      - backend

networks:
  nginxproxy_frontend:
    external: true
  backend:
    driver: bridge
