version: '3'

services:

  arasaac:
    image: nginx
    hostname: newarasaac
    container_name: newarasaac
    volumes:
       - ./arasaac-conf/:/etc/nginx/conf.d:ro
       - ./arasaac-code/:/usr/share/nginx/html
    environment:
      LETSENCRYPT_HOST: "beta.arasaac.org"
      LETSENCRYPT_EMAIL: "juandacorreo@gmail.com"
      VIRTUAL_HOST: "beta.arasaac.org"
    networks:
      - nginxproxy_frontend
  webstatic:
    image: nginx
    hostname: webstatic
    container_name: webstatic
    volumes:
       - ./materials:/usr/share/nginx/html:ro
       - ./webstatic-conf/:/etc/nginx/conf.d:ro
    environment:
      LETSENCRYPT_HOST: "static.arasaac.org"
      LETSENCRYPT_EMAIL: "juandacorreo@gmail.com"
      VIRTUAL_HOST: "static.arasaac.org"
    networks:
      - nginxproxy_frontend

  arasaac-api:
    hostname: arasaac-api
    container_name: arasaac-api
    build:
      context: ./arasaac-api
      dockerfile: node-dockerfile.yml
    command: yarn start
    depends_on:
      - mongodb
    volumes:
    - ./arasaac-api/app:/app
    - ./materials:/app/materials
    - /app/node_modules
    environment:
      LETSENCRYPT_HOST: "api.arasaac.org"
      LETSENCRYPT_EMAIL: "juandacorreo@gmail.com"
      VIRTUAL_HOST: "api.arasaac.org"
    networks:
      - nginxproxy_frontend
      - backend
    ports:
      - "9229:9229"
  
  arasaac-watcher:
    hostname: arasaac-watcher
    container_name: arasaac-watcher
    build:
      context: ./arasaac-watcher
      dockerfile: node-dockerfile.yml
    command: yarn start
    volumes:
    - ./arasaac-watcher/app:/app
    - ./materials:/app/materials
    - /app/node_modules

  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo
    volumes:
      - ./arasaac-api/dump:/docker-entrypoint-initdb.d
      - ./arasaac-api/dbdata:/data/db
    networks:
      - backend
    ports:
      - "27000:27017"

networks:
  nginxproxy_frontend:
    external: true
  backend:
    driver: bridge
