version: "3"

services:
  api:
    command: sh -c "./wait && npm start"
    ports:
      - "9229:9229"

  privateapi:
    command: sh -c "./wait && npm start"
    ports:
      - "9227:9229"

  auth:
    command: sh -c "./wait && npm start"
    ports:
      - "9228:9229"
      - "5000:80"
    environment:
      DEBUG: "oauth2orize"

  watcher:
    hostname: watcher
    container_name: watcher
    build:
      context: ./watcher
    ports:
      - "9225:9229"
    command: npm start
    volumes:
      - ./watcher:/app
      - ${MATERIAL_DIR}:/materials
      - /app/node_modules
      - /app/.config
    environment:
      NODE_ENV: $NODE_ENV
    restart: always

networks:
  nginxproxy_frontend:
    external: true
  backend:
    driver: bridge
