version: '3'

services:

  arasaac:
    image: nginx
    hostname: newarasaac
    container_name: newarasaac
    volumes:
       - ./arasaac-conf/:/etc/nginx/conf.d:ro
       - ./arasaac-code/:/usr/share/nginx/html
    environment:
      LETSENCRYPT_HOST: "beta.arasaac.org"
      LETSENCRYPT_EMAIL: "juandacorreo@gmail.com"
      VIRTUAL_HOST: "beta.arasaac.org"
    networks:
      - nginxproxy_frontend
  webstatic:
    image: nginx
    hostname: webstatic
    container_name: webstatic
    volumes:
       - ./materiales:/usr/share/nginx/html:ro
       - ./webstatic-conf/:/etc/nginx/conf.d:ro
    environment:
      LETSENCRYPT_HOST: "static.arasaac.org"
      LETSENCRYPT_EMAIL: "juandacorreo@gmail.com"
      VIRTUAL_HOST: "static.arasaac.org"
    networks:
      - nginxproxy_frontend

  api-arasaac:
    hostname: api-arasaac
    container_name: api-arasaac
    build:
      context: ./api-arasaac
      dockerfile: node-dockerfile.yml
    command: yarn start
    depends_on:
      - mongodb
    volumes:
    - ./api-arasaac/app:/app
    - ./materiales:/app/materiales
    - /app/node_modules
    environment:
      LETSENCRYPT_HOST: "api.arasaac.org"
      LETSENCRYPT_EMAIL: "juandacorreo@gmail.com"
      VIRTUAL_HOST: "api.arasaac.org"
    networks:
      - nginxproxy_frontend
      - backend

  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo
    volumes:
      - ./api-arasaac/dump:/docker-entrypoint-initdb.d
      - ./api-arasaac/dbdata:/data/db
    networks:
      - backend

networks:
  nginxproxy_frontend:
    external: true
  backend:
    driver: bridge
