version: "3"

services:
  api:
    command: npm start
    ports:
      - "9229:9229"
    volumes:
      - ./api:/app

  privateapi:
    command: npm start
    ports:
      - "9227:9229"
    volumes:
      - ./privateApi/node_modules:/app/node_modules

  auth:
    command: npm start
    depends_on:
      - mongodb
    ports:
      - "9228:9229"
      - "5000:80"
    volumes:
      - ./auth/node_modules:/app/node_modules
    environment:
      DEBUG: "oauth2orize"

  mongodb:
    ports:
      - "27000:27017"

networks:
  nginxproxy_frontend:
    external: true
  backend:
    driver: bridge
