version: "3"

services:
  api:
    hostname: api
    container_name: api
    build:
      context: ./api
    command: sh -c "./wait && npm run serve"
    depends_on:
      - mongodb
      - auth
    volumes:
      - ./api:/app
      - ${MATERIAL_DIR}:/materials
      - /app/.config
      - ${SVG_DIR}:/svg:ro
      - ${IMAGE_DIR}:/pictograms
      - api-libs:/app/node_modules
    environment:
      LETSENCRYPT_HOST: "api.arasaac.org"
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      VIRTUAL_HOST: "api.arasaac.org"
      NODE_ENV: $NODE_ENV
      LOG_LEVEL: $LOG_LEVEL
      MONGO_DB_USER: $MONGO_DB_USER
      MONGO_DB_PWD: $MONGO_DB_PWD
      WAIT_HOSTS: mongodb:27017
    networks:
      - nginxproxy_frontend
      - backend
    restart: always

  privateapi:
    hostname: privateapi
    container_name: privateapi
    build:
      context: ./privateApi
    command: sh -c "./wait && npm run serve"
    depends_on:
      - mongodb
      - auth
    volumes:
      - ./privateApi:/app
      - ${MATERIAL_DIR}:/materials
      - ./locutions:/locutions
      - ./certs:/root/.ssh
      - ${SITEMAP_DIR}:/sitemap
      - ${IMAGE_DIR}:/pictograms
      - ${CONJUGATIONS_DIR}:/conjugations
      - ${SVG_DIR}:/svg:rw
      - ./tmp:/tmp
      - /app/.config
      - privateapi-libs:/app/node_modules
    environment:
      LETSENCRYPT_HOST: "privateapi.arasaac.org"
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      VIRTUAL_HOST: "privateapi.arasaac.org"
      NODE_ENV: $NODE_ENV
      EMAIL_FROM: $EMAIL_FROM
      EMAIL_USER: $EMAIL_USER
      EMAIL_PASSWORD: $EMAIL_PASSWORD
      EMAIL_SMTP: $EMAIL_SMTP
      SFTP_SERVER: $SFTP_SERVER
      LOG_LEVEL: $LOG_LEVEL
      CROWDIN_ARASAAC_API_KEY: $CROWDIN_ARASAAC_API_KEY
      CROWDIN_ADMIN_ARASAAC_API_KEY: $CROWDIN_ADMIN_ARASAAC_API_KEY
      CRONTAB: $CRONTAB
      MONGO_DB_USER: $MONGO_DB_USER
      MONGO_DB_PWD: $MONGO_DB_PWD
      WAIT_HOSTS: mongodb:27017
    networks:
      - nginxproxy_frontend
      - backend
    restart: always

  auth:
    hostname: auth
    container_name: auth
    build:
      context: ./auth
    command: sh -c "./wait && npm run serve"
    depends_on:
      - mongodb
    volumes:
      - ./auth:/app
      - /app/.config
      - auth-libs:/app/node_modules
    environment:
      LETSENCRYPT_HOST: "auth.arasaac.org"
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      VIRTUAL_HOST: "auth.arasaac.org"
      NODE_ENV: $NODE_ENV
      MONGO_DB_USER: $MONGO_DB_USER
      MONGO_DB_PWD: $MONGO_DB_PWD
      WAIT_HOSTS: mongodb:27017
    networks:
      - nginxproxy_frontend
      - backend
    restart: always

  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:3.6
    volumes:
      - ./mongodb/dump:/docker-entrypoint-initdb.d
      - ./mongodb/dbdata:/data/db
      - ./mongodb/backup:/data/backup
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_DB_PWD
    networks:
      - backend
    restart: always
    ports:
      - "27000:27017"

networks:
  nginxproxy_frontend:
    external: true
  backend:
    driver: bridge

volumes:
  api-libs:
  privateapi-libs:
  auth-libs:
