version: "3"

services:
  api:
    command: npm start
    ports:
      - "9229:9229"
    volumes:
      - ./api:/app
      - /app/node_modules

  privateapi:
    command: npm start
    ports:
      - "9227:9229"
    volumes:
      - /app/node_modules

  auth:
    command: npm start
    depends_on:
      - mongodb
    ports:
      - "9228:9229"
      - "5000:80"
    volumes:
      - /app/node_modules

  mongodb:
    ports:
      - "27000:27017"

networks:
  nginxproxy_frontend:
    external: true
  backend:
    driver: bridge
