version: "3"

services:
  api:
    hostname: api
    container_name: api
    build:
      context: ./api
    command: npm run serve
    depends_on:
      - mongodb
      - auth
    volumes:
      - ${MATERIAL_DIR}:/app/materials
      - /app/.config
      - ${SVG_DIR}:/app/svg:ro
      - ${IMAGE_DIR}:/app/pictograms
      - /app/node_modules
    environment:
      LETSENCRYPT_HOST: "api.arasaac.org"
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      VIRTUAL_HOST: "api.arasaac.org"
      NODE_ENV: $NODE_ENV
      LOG_LEVEL: $LOG_LEVEL
      MONGO_DB_USER: $MONGO_DB_USER
      MONGO_DB_PWD: $MONGO_DB_PWD
    networks:
      - nginxproxy_frontend
      - backend
    restart: always

  privateapi:
    hostname: privateapi
    container_name: privateapi
    build:
      context: ./privateApi
    command: npm run serve
    depends_on:
      - mongodb
      - auth
    volumes:
      - ./privateApi:/app
      - ${MATERIAL_DIR}:/app/materials
      - ./locutions:/app/locutions
      - ./certs:/root/.ssh
      - ${IMAGE_DIR}:/app/pictograms
      - ${CONJUGATIONS_DIR}:/app/conjugations
      - ${SVG_DIR}:/app/svg:rw
      - ./tmp:/app/tmp
      - /app/.config
      - /app/node_modules
    environment:
      LETSENCRYPT_HOST: "privateapi.arasaac.org"
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      VIRTUAL_HOST: "privateapi.arasaac.org"
      NODE_ENV: $NODE_ENV
      EMAIL_FROM: $EMAIL_FROM
      EMAIL_USER: $EMAIL_USER
      EMAIL_PASSWORD: $EMAIL_PASSWORD
      EMAIL_SMTP: $EMAIL_SMTP
      SFTP_SERVER: $SFTP_SERVER
      LOG_LEVEL: $LOG_LEVEL
      MONGO_DB_USER: $MONGO_DB_USER
      MONGO_DB_PWD: $MONGO_DB_PWD
    networks:
      - nginxproxy_frontend
      - backend
    restart: always

  auth:
    hostname: auth
    container_name: auth
    build:
      context: ./auth
    command: npm run serve
    depends_on:
      - mongodb
    volumes:
      - ./auth:/app
      - /app/.config
      - /app/node_modules
    environment:
      LETSENCRYPT_HOST: "auth.arasaac.org"
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      VIRTUAL_HOST: "auth.arasaac.org"
      NODE_ENV: $NODE_ENV
      MONGO_DB_USER: $MONGO_DB_USER
      MONGO_DB_PWD: $MONGO_DB_PWD
    networks:
      - nginxproxy_frontend
      - backend
    restart: always

  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:3.6
    volumes:
      - ./mongodb/dump:/docker-entrypoint-initdb.d
      - ./mongodb/dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_DB_PWD
    networks:
      - backend
    restart: always

networks:
  nginxproxy_frontend:
    external: true
  backend:
    driver: bridge
