version: '3'

services:

  db:
    hostname: db
    image: mysql:5.5
    container_name: db
    volumes:
      - ./bbdd:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    env_file:
      - .env

    networks:
      - backend

  phpmyadmin:
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      VIRTUAL_HOST: "phpmyadmin.arasaac.org,www.phpmyadmin.arasaac.org"
    env_file:
      - .env
    restart: always
    volumes:
      - /sessions
    networks:
      - nginxproxy_frontend
      - backend

networks:
  nginxproxy_frontend:
    external: true
  backend:
    driver: bridge
