version: "3"

services:
  db:
    hostname: db
    image: mysql:5.5
    container_name: db
    volumes:
      - ./bbdd:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - backend

  phpmyadmin:
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      VIRTUAL_HOST: "phpmyadmin.arasaac.org,www.phpmyadmin.arasaac.org"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    volumes:
      - /sessions
    networks:
      - nginxproxy_frontend
      - backend

  migration:
    hostname: migration
    container_name: migration
    build:
      context: ./migration
      dockerfile: Dockerfile
    working_dir: /app
    command: python /app/pictos.py
    #command: ./start.sh
    #command: tail -100f /dev/null
    env_file:
      - .env
    networks:
      - backend
      - newarasaac_backend
    depends_on:
      - db
    volumes:
      - "./data:/app/data"
      - "../newarasaac/locutions:/app/locutions"
      - "../newarasaac/svg:/app/svg"
    ports:
      - 5005:5000
networks:
  nginxproxy_frontend:
    external: true
  backend:
    driver: bridge
  newarasaac_backend:
    external: true
