version: '3'

services:

  db:
    hostname: db
    image: mysql:5.5
    container_name: db
    volumes:
      - ./bbdd:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - backend

  phpmyadmin:
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      VIRTUAL_HOST: "phpmyadmin.arasaac.org,www.phpmyadmin.arasaac.org"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    volumes:
      - /sessions
    networks:
      - nginxproxy_frontend
      - backend

  migration:
    hostname: migration
    container_name: migration
    build: 
      context: .
      dockerfile: python-dockerfile.yml
    working_dir: /app
    #command: ./start.sh
    command: ./start.sh
    env_file:
      - .env
    networks:
      - backend
      - newarasaac_backend
    depends_on:
      - db
    volumes:
      - "./data:/app/data"
      - "../newarasaac/locutions:/app/locutions"
      - "../newarasaac/svg:/app/svg"  

networks:
  nginxproxy_frontend:
    external: true
  backend:
    driver: bridge
  newarasaac_backend:
    external: true
