FROM node:8.2.1

MAINTAINER juandacorreo@gmail.com

ENV NODE_ENV=development 
ENV PORT=80

# Set working directory
RUN mkdir /app
WORKDIR /app
ENV HOME=/app

# Install dependencies
COPY package.json $HOME/
RUN npm install

EXPOSE $PORT
