version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  frontend:
    driver: bridge

services:
  traefik:
    image: 'traefik:v2.9.6'
    container_name: 'traefik'
    ports:
      - '80:80'
      - '443:443'
      # for metrics
      - '8082:8082'
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/ssl:/ssl

    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certresolver=production
      - traefik.http.routers.dashboard.rule=Host(`proxy.arasaac.org`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=user:$$2y$$05$$wB0t/mzh3MIMrikaN5QTz.90jYend8SvsTeIaENxySipurdk0ZicK
    networks:
      - frontend
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '200m'
        max-file: '5'
