version: '3'

services:
  mongodb:
#    build:
    #context: ./mongo
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./dbdata:/data/db
  node:
    build:
      context: .
      dockerfile: node-dockerfile.yml
    command: yarn start
    ports:
      - "8001:80"
    depends_on: 
      - mongodb
    volumes:
    - ./app:/app
    - /app/node_modules
  apidocs:
    image: swaggerapi/swagger-ui
    environment:
     SWAGGER_JSON: "./config/arasaac.json"    
    ports:
    - "8002:8080"
    volumes:
    - ./app/public/arasaac.json:/config/arasaac.json 
  webmongo:
    image: mongo-express
    ports:
      - "8003:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_OPTIONS_EDITORTHEME: default
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: arasaac



      
